#ifndef DEVICE_RUNTIME_CONFIG_H
#define DEVICE_RUNTIME_CONFIG_H

#include "driver/gpio.h"
#include "driver/spi_master.h"

#define DEVICE_FIRMWARE_VERSION "esp32s3-light-0.2"

/*
 * Replace these defaults before flashing real hardware. They are compile-time
 * defaults for the first ESP32-S3 port; NVS/USB setup can be added later.
 */
#ifndef DEVICE_WIFI_SSID
#define DEVICE_WIFI_SSID "CHANGE_ME"
#endif

#ifndef DEVICE_WIFI_PASSWORD
#define DEVICE_WIFI_PASSWORD "CHANGE_ME"
#endif

#ifndef DEVICE_SERVER_HOST
#define DEVICE_SERVER_HOST "192.168.1.10"
#endif

#ifndef DEVICE_SERVER_PORT
#define DEVICE_SERVER_PORT 80u
#endif

#ifndef DEVICE_ID
#define DEVICE_ID "esp32s3-light-001"
#endif

#define DEVICE_RUNTIME_POLL_SLEEP_MS 50u

#define DEVICE_TIME_SYNC_ATTEMPT_COUNT 3u
#define DEVICE_TIME_SYNC_SAMPLE_DELAY_MS 50u
#define DEVICE_TIME_SYNC_RETRY_DELAY_MS 5000u
#define DEVICE_TIME_SYNC_PERIOD_MS 7200000u
#define DEVICE_TIME_SYNC_REQUEST_TIMEOUT_MS 20000u

#define DEVICE_HEALTH_REPORT_INTERVAL_MS 36000000u
#define DEVICE_HEALTH_RETRY_MS 5000u
#define DEVICE_HEALTH_REQUEST_TIMEOUT_MS 10000u

#define DEVICE_SOUND_EVENT_POST_CAPTURE_MS 0u
#define DEVICE_SOUND_EVENT_UPLOAD_TIMEOUT_MS 30000u

#define DEVICE_STARTUP_CONSOLE_WINDOW_MS 7000u
#define DEVICE_WIFI_CONNECT_TIMEOUT_MS 20000u

#define DEVICE_AUDIO_SAMPLE_RATE_HZ 48000u
#define DEVICE_AUDIO_TARGET_SAMPLE_RATE_HZ 16000u
#define DEVICE_AUDIO_CAPTURE_FRAMES 48u
#define DEVICE_I2S_TO_PCM16_SHIFT 16

#define DEVICE_MIC_PIN_BCLK GPIO_NUM_4
#define DEVICE_MIC_PIN_LRCLK GPIO_NUM_5
#define DEVICE_MIC_PIN_DOUT GPIO_NUM_6
#define DEVICE_MIC_PIN_SEL GPIO_NUM_7
#define DEVICE_MIC_SEL_LEVEL 0

#define DEVICE_SD_SPI_HOST SPI2_HOST
#define DEVICE_SD_PIN_CS GPIO_NUM_10
#define DEVICE_SD_PIN_MOSI GPIO_NUM_11
#define DEVICE_SD_PIN_SCK GPIO_NUM_12
#define DEVICE_SD_PIN_MISO GPIO_NUM_13

#define DEVICE_SD_BLOCK_SIZE 512u
#define DEVICE_SD_AUDIO_BUFFER_SECONDS 5u
#define DEVICE_SD_AUDIO_BUFFER_BYTES (DEVICE_SD_AUDIO_BUFFER_SECONDS * DEVICE_AUDIO_TARGET_SAMPLE_RATE_HZ * 2u)
#define DEVICE_SD_AUDIO_BUFFER_BLOCKS ((DEVICE_SD_AUDIO_BUFFER_BYTES + DEVICE_SD_BLOCK_SIZE - 1u) / DEVICE_SD_BLOCK_SIZE)
#define DEVICE_SD_AUDIO_BUFFER_CAPACITY_BYTES (DEVICE_SD_AUDIO_BUFFER_BLOCKS * DEVICE_SD_BLOCK_SIZE)
#define DEVICE_SD_BUFFER_BASE_BLOCK 32768u

#endif
