#ifndef DEVICE_RUNTIME_CONFIG_H
#define DEVICE_RUNTIME_CONFIG_H

#define DEVICE_SYS_CLOCK_KHZ 80000u

#define DEVICE_RUNTIME_POLL_SLEEP_MS 50u

#define DEVICE_TIME_SYNC_ATTEMPT_COUNT 3u
#define DEVICE_TIME_SYNC_SAMPLE_DELAY_MS 50u
#define DEVICE_TIME_SYNC_RETRY_DELAY_MS 5000u
#define DEVICE_TIME_SYNC_PERIOD_MS 7200000u
#define DEVICE_TIME_SYNC_REQUEST_TIMEOUT_MS 20000u

#define DEVICE_HEALTH_REPORT_INTERVAL_MS 36000000u
#define DEVICE_HEALTH_RETRY_MS 5000u
#define DEVICE_HEALTH_REQUEST_TIMEOUT_MS 10000u

#define DEVICE_SOUND_EVENT_POST_CAPTURE_MS 0u
#define DEVICE_SOUND_EVENT_UPLOAD_TIMEOUT_MS 30000u

#endif
